### ISSUE TITLE
Math Magicians: refactor with hooks- code explanation 

### ISSUE THREAD

**Issue by MarkoKermi** [MarkoKermi/math_magicians#4]
- [ ]  The code imports the React library and the useState hook from React, as well as a custom function called "calculate" and a CSS file.

- [ ]  The code defines a function component called "Calculator" that returns a container div with a wrapper div inside it. The wrapper div contains an input element that displays the calculator's output and a series of buttons that can be clicked to perform math calculation.

- [ ]  The component uses the useState hook to define a "result" state variable that keeps track of the current calculator input and operation. The initial state of "result" is an object with three properties: "total", "next", and "operation".

- [ ] The component defines a "handleClick" function that is called whenever a button is clicked. This function calls the "calculate" function and passes in the current "result" state and the text content of the button that was clicked. The result of the calculation is then used to update the "result" state using the "setResult" function.

- [ ] The component returns the container div with the wrapper div and its child elements. When a button is clicked, the "handleClick" function is called and the input and state are updated to reflect the user's input and the result of the calculation.

**Comment by mckent05** [comment]
Hi @MarkoKermi, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👏 👏 
- You have shown a good understanding, from your explanation, about the use of hooks in react 👍 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
